jobs:
    
  test:
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Test Step
          command: gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .

  package:
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Artifact Step
          command: gradle jar
      - store_artifacts:
          path: build/libs
          desitnation: prefix
      - persist_to_workspace:
          root: .
          paths:
            - .
          #  - project/build/libs/gildedrose-0.0.1-SNAPSHOT.jar
  
  dockerize:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1

workflows:
  version: 2
  test_and_package:
    jobs:
      - test
      - package:
          requires:
            - test
      - dockerize:
          requires:
            - package
