jobs:
  test:
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Test Step
          command: gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: test
          paths: 
            - . 
  package:
    require: test
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Artifact Step
          command: gradle jar
      - store_artifacts:
          path: build/libs
          desitnation: prefix


workflows:
  version: 2
  test_and_package:
    jobs:
      - test
      - package:
          requires:
            - test
