jobs:
  test:
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Test Step
          command: gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: ~/
          paths:
            - /home/circleci/project/build/test-results

  package:
    require: test
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Artifact Step
          command: gradle jar
      - store_artifacts:
          path: build/libs
          desitnation: prefix
      - persist_to_workspace:
          root: ~/
          paths:
            - /home/circleci/project/build/libs/gildedrose-0.0.1-SNAPSHOT.jar


workflows:
  version: 2
  test_and_package:
    jobs:
      - test
      - package:
          requires:
            - test
